export const APP_CONSTANTS = {
  API_PREFIX: '/api/v1',
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  PASSWORD_SALT_ROUNDS: 12,
  REFRESH_TOKEN_COOKIE_NAME: 'refreshToken',
  REFRESH_TOKEN_EXPIRY_MS: 7 * 24 * 60 * 60 * 1000, // 7 days
  DEFAULT_DISTRICT: 'Nashik',
  DEFAULT_STATE: 'Maharashtra',
  MATCH_SCORE_THRESHOLD: 0.5,
};
