export const ROUTES = {
  PUBLIC: {
    LANDING: '/',
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    UNAUTHORIZED: '/unauthorized',
    NOT_FOUND: '/404',
  },
  BUYER: {
    DASHBOARD: '/buyer/dashboard',
    REQUIREMENTS: '/buyer/requirements',
    REQUIREMENTS_NEW: '/buyer/requirements/new',
    REQUIREMENTS_EDIT: '/buyer/requirements/:id/edit',
    REQUESTS: '/buyer/requests',
    TRANSACTIONS: '/buyer/transactions',
    TRANSACTION_DETAIL: '/buyer/transactions/:id',
    PROFILE: '/buyer/profile',
  },
  FPO: {
    DASHBOARD: '/fpo/dashboard',
    FARMERS: '/fpo/farmers',
    DEMAND: '/fpo/demand',
    BUNDLE: '/fpo/bundle',
    TRANSACTIONS: '/fpo/transactions',
    TRANSACTION_DETAIL: '/fpo/transactions/:id',
    PROFILE: '/fpo/profile',
  },
  ADMIN: {
    OVERVIEW: '/admin/overview',
    FARMERS: '/admin/farmers',
    FARMER_DETAIL: '/admin/farmers/:id',
    BUYERS: '/admin/buyers',
    FPOS: '/admin/fpos',
    FPO_DETAIL: '/admin/fpos/:id',
    CROPS: '/admin/crops',
    MARKET_PRICES: '/admin/market-prices',
    WEATHER: '/admin/weather',
    RECOMMENDATIONS: '/admin/recommendations',
    TRANSACTIONS: '/admin/transactions',
    TRANSACTION_DETAIL: '/admin/transactions/:id',
    ANALYTICS: '/admin/analytics',
    SYSTEM_HEALTH: '/admin/system-health',
  },
};
